"""add_phoi_du_items_to_phieu_nhap_phoi_song

Revision ID: 061de93d4bd0
Revises: pd001_add_phoi_du_so_luong
Create Date: 2026-06-29 17:26:55.803502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '061de93d4bd0'
down_revision: Union[str, None] = 'pd001_add_phoi_du_so_luong'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phieu_nhap_phoi_song', sa.Column('phoi_du_items', sa.JSON(), nullable=True))
    op.drop_index('ix_phieu_nhap_phoi_song_ngay', table_name='phieu_nhap_phoi_song')
    op.drop_index('ix_phieu_nhap_phoi_song_production_order_id', table_name='phieu_nhap_phoi_song')
    op.drop_index('ix_phieu_nhap_phoi_song_items_phieu_id', table_name='phieu_nhap_phoi_song_items')
    op.drop_index('ix_production_plan_lines_po_item_id', table_name='production_plan_lines')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_production_plan_lines_po_item_id', 'production_plan_lines', ['production_order_item_id'], unique=False)
    op.create_index('ix_phieu_nhap_phoi_song_items_phieu_id', 'phieu_nhap_phoi_song_items', ['phieu_id'], unique=False)
    op.create_index('ix_phieu_nhap_phoi_song_production_order_id', 'phieu_nhap_phoi_song', ['production_order_id'], unique=False)
    op.create_index('ix_phieu_nhap_phoi_song_ngay', 'phieu_nhap_phoi_song', [sa.text('ngay DESC'), sa.text('id DESC')], unique=False)
    op.drop_column('phieu_nhap_phoi_song', 'phoi_du_items')
    # ### end Alembic commands ###
