"""quote_phan_xuong_nv_theo_doi

Revision ID: 09797a29e0d7
Revises: a1b2c3d4e5f6
Create Date: 2026-04-30 21:11:37.591487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '09797a29e0d7'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('phieu_nhap_kho')
    op.drop_table('phieu_xuat_kho_item')
    op.drop_table('phieu_xuat_kho')
    op.drop_table('phieu_nhap_kho_item')
    op.create_foreign_key(None, 'phieu_in', 'may_sau_in', ['may_sau_in_id'], ['id'])
    op.drop_index('ix_production_orders_ngay_lenh', table_name='production_orders')
    op.create_foreign_key(None, 'production_orders', 'phan_xuong', ['phan_xuong_id'], ['id'])
    op.create_foreign_key(None, 'production_orders', 'warehouses', ['kho_sx_id'], ['id'])
    op.create_foreign_key(None, 'production_orders', 'phap_nhan', ['phap_nhan_sx_id'], ['id'])
    op.drop_index('ix_quotes_ngay_bao_gia', table_name='quotes')
    op.create_foreign_key(None, 'quotes', 'users', ['nv_theo_doi_id'], ['id'])
    op.create_foreign_key(None, 'quotes', 'phan_xuong', ['phan_xuong_id'], ['id'])
    op.create_foreign_key(None, 'quotes', 'phap_nhan', ['phap_nhan_id'], ['id'])
    op.drop_index('ix_sales_orders_ngay_don', table_name='sales_orders')
    op.create_foreign_key(None, 'sales_orders', 'phap_nhan', ['phap_nhan_sx_id'], ['id'])
    op.create_foreign_key(None, 'sales_orders', 'phap_nhan', ['phap_nhan_id'], ['id'])
    op.drop_index('ix_scan_log_created_at', table_name='scan_log')
    op.drop_index('ix_scan_log_may_scan_id', table_name='scan_log')
    op.drop_index('ix_scan_log_so_lsx', table_name='scan_log')
    op.create_foreign_key(None, 'warehouses', 'phan_xuong', ['phan_xuong_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'warehouses', type_='foreignkey')
    op.create_index('ix_scan_log_so_lsx', 'scan_log', ['so_lsx'], unique=False)
    op.create_index('ix_scan_log_may_scan_id', 'scan_log', ['may_scan_id'], unique=False)
    op.create_index('ix_scan_log_created_at', 'scan_log', ['created_at'], unique=False)
    op.drop_constraint(None, 'sales_orders', type_='foreignkey')
    op.drop_constraint(None, 'sales_orders', type_='foreignkey')
    op.create_index('ix_sales_orders_ngay_don', 'sales_orders', ['ngay_don'], unique=False)
    op.drop_constraint(None, 'quotes', type_='foreignkey')
    op.drop_constraint(None, 'quotes', type_='foreignkey')
    op.drop_constraint(None, 'quotes', type_='foreignkey')
    op.create_index('ix_quotes_ngay_bao_gia', 'quotes', ['ngay_bao_gia'], unique=False)
    op.drop_constraint(None, 'production_orders', type_='foreignkey')
    op.drop_constraint(None, 'production_orders', type_='foreignkey')
    op.drop_constraint(None, 'production_orders', type_='foreignkey')
    op.create_index('ix_production_orders_ngay_lenh', 'production_orders', ['ngay_lenh'], unique=False)
    op.drop_constraint(None, 'phieu_in', type_='foreignkey')
    op.create_table('phieu_nhap_kho_item',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('phieu_nhap_kho_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('paper_material_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('other_material_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ten_hang', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('don_vi', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('so_luong', sa.NUMERIC(precision=12, scale=3), autoincrement=False, nullable=False),
    sa.Column('don_gia', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=False),
    sa.Column('thanh_tien', sa.NUMERIC(precision=16, scale=2), autoincrement=False, nullable=False),
    sa.Column('ghi_chu', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['other_material_id'], ['other_materials.id'], name='phieu_nhap_kho_item_other_material_id_fkey'),
    sa.ForeignKeyConstraint(['paper_material_id'], ['paper_materials.id'], name='phieu_nhap_kho_item_paper_material_id_fkey'),
    sa.ForeignKeyConstraint(['phieu_nhap_kho_id'], ['phieu_nhap_kho.id'], name='phieu_nhap_kho_item_phieu_nhap_kho_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='phieu_nhap_kho_item_pkey')
    )
    op.create_table('phieu_xuat_kho',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('phieu_xuat_kho_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('so_phieu', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('warehouse_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ngay', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('loai_xuat', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('ghi_chu', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('trang_thai', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='phieu_xuat_kho_created_by_fkey'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name='phieu_xuat_kho_warehouse_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='phieu_xuat_kho_pkey'),
    sa.UniqueConstraint('so_phieu', name='phieu_xuat_kho_so_phieu_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('phieu_xuat_kho_item',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('phieu_xuat_kho_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('paper_material_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('other_material_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ten_hang', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('don_vi', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('so_luong', sa.NUMERIC(precision=12, scale=3), autoincrement=False, nullable=False),
    sa.Column('don_gia', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=False),
    sa.Column('thanh_tien', sa.NUMERIC(precision=16, scale=2), autoincrement=False, nullable=False),
    sa.Column('ghi_chu', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['other_material_id'], ['other_materials.id'], name='phieu_xuat_kho_item_other_material_id_fkey'),
    sa.ForeignKeyConstraint(['paper_material_id'], ['paper_materials.id'], name='phieu_xuat_kho_item_paper_material_id_fkey'),
    sa.ForeignKeyConstraint(['phieu_xuat_kho_id'], ['phieu_xuat_kho.id'], name='phieu_xuat_kho_item_phieu_xuat_kho_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='phieu_xuat_kho_item_pkey')
    )
    op.create_table('phieu_nhap_kho',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('so_phieu', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('warehouse_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ngay', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('loai_nhap', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('nha_cung_cap_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ghi_chu', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('trang_thai', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='phieu_nhap_kho_created_by_fkey'),
    sa.ForeignKeyConstraint(['nha_cung_cap_id'], ['suppliers.id'], name='phieu_nhap_kho_nha_cung_cap_id_fkey'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name='phieu_nhap_kho_warehouse_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='phieu_nhap_kho_pkey'),
    sa.UniqueConstraint('so_phieu', name='phieu_nhap_kho_so_phieu_key')
    )
    # ### end Alembic commands ###
