"""add_so_luot_in_to_phieu_in

Revision ID: 174b5ce65449
Revises: 16cc3e36dba0
Create Date: 2026-06-29 20:31:54.343916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '174b5ce65449'
down_revision: Union[str, None] = '16cc3e36dba0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phieu_in', sa.Column('so_luot_in', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('phieu_in', 'so_luot_in')
    # ### end Alembic commands ###
