"""phoi_du_tracking_and_defect_warehouse_id

Revision ID: 197f6b82910c
Revises: ba9dbfeb64fa
Create Date: 2026-06-27 13:24:04.949741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '197f6b82910c'
down_revision: Union[str, None] = 'ba9dbfeb64fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('defect_records', sa.Column('warehouse_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'defect_records', 'warehouses', ['warehouse_id'], ['id'])
    op.alter_column('delivery_post_tasks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_index('ix_dpt_delivery_id', table_name='delivery_post_tasks')
    op.drop_index('ix_dpt_trang_thai', table_name='delivery_post_tasks')
    op.create_index(op.f('ix_delivery_post_tasks_delivery_id'), 'delivery_post_tasks', ['delivery_id'], unique=False)
    op.create_index(op.f('ix_delivery_post_tasks_trang_thai'), 'delivery_post_tasks', ['trang_thai'], unique=False)
    op.add_column('phieu_nhap_phoi_song', sa.Column('phoi_du_trang_thai', sa.String(length=30), nullable=True))
    op.add_column('phieu_nhap_phoi_song', sa.Column('phoi_du_ghi_chu', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('phieu_nhap_phoi_song', 'phoi_du_ghi_chu')
    op.drop_column('phieu_nhap_phoi_song', 'phoi_du_trang_thai')
    op.drop_index(op.f('ix_delivery_post_tasks_trang_thai'), table_name='delivery_post_tasks')
    op.drop_index(op.f('ix_delivery_post_tasks_delivery_id'), table_name='delivery_post_tasks')
    op.create_index('ix_dpt_trang_thai', 'delivery_post_tasks', ['trang_thai'], unique=False)
    op.create_index('ix_dpt_delivery_id', 'delivery_post_tasks', ['delivery_id'], unique=False)
    op.alter_column('delivery_post_tasks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_constraint(None, 'defect_records', type_='foreignkey')
    op.drop_column('defect_records', 'warehouse_id')
    # ### end Alembic commands ###
