"""add_tk_loai_tien_to_doi_tru_chung_tu

Revision ID: 499c0678b168
Revises: zmh034
Create Date: 2026-06-18 22:47:49.638161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '499c0678b168'
down_revision: Union[str, None] = 'zmh034'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doi_tru_chung_tu', sa.Column('tk_no', sa.String(length=10), nullable=True))
    op.add_column('doi_tru_chung_tu', sa.Column('tk_co', sa.String(length=10), nullable=True))
    op.add_column('doi_tru_chung_tu', sa.Column('loai_tien', sa.String(length=10), server_default='VND', nullable=False))
    op.drop_index('ix_doi_tru_chung_tu_ngay', table_name='doi_tru_chung_tu')
    op.drop_index('ix_doi_tru_chung_tu_phap_nhan', table_name='doi_tru_chung_tu')
    op.drop_index('ix_doi_tru_chung_tu_supplier', table_name='doi_tru_chung_tu')
    op.create_index(op.f('ix_doi_tru_chung_tu_ngay_doi_tru'), 'doi_tru_chung_tu', ['ngay_doi_tru'], unique=False)
    op.create_index(op.f('ix_doi_tru_chung_tu_phap_nhan_id'), 'doi_tru_chung_tu', ['phap_nhan_id'], unique=False)
    op.create_index(op.f('ix_doi_tru_chung_tu_supplier_id'), 'doi_tru_chung_tu', ['supplier_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_doi_tru_chung_tu_supplier_id'), table_name='doi_tru_chung_tu')
    op.drop_index(op.f('ix_doi_tru_chung_tu_phap_nhan_id'), table_name='doi_tru_chung_tu')
    op.drop_index(op.f('ix_doi_tru_chung_tu_ngay_doi_tru'), table_name='doi_tru_chung_tu')
    op.create_index('ix_doi_tru_chung_tu_supplier', 'doi_tru_chung_tu', ['supplier_id'], unique=False)
    op.create_index('ix_doi_tru_chung_tu_phap_nhan', 'doi_tru_chung_tu', ['phap_nhan_id'], unique=False)
    op.create_index('ix_doi_tru_chung_tu_ngay', 'doi_tru_chung_tu', ['ngay_doi_tru'], unique=False)
    op.drop_column('doi_tru_chung_tu', 'loai_tien')
    op.drop_column('doi_tru_chung_tu', 'tk_co')
    op.drop_column('doi_tru_chung_tu', 'tk_no')
    # ### end Alembic commands ###
