"""add_nv_theo_doi_id_to_sales_orders

Revision ID: 72a4eb5c34cf
Revises: zmh052
Create Date: 2026-06-30 20:02:31.425299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72a4eb5c34cf'
down_revision: Union[str, None] = 'zmh052'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'be_hai_manh',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('products', 'co_be',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('products', 'be_lo',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('products', 'do_kho',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('products', 'do_phu',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('products', 'co_tem_offset',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('products', 'tem_sp_per_to',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('products', 'tem_waste_to',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('products', 'tem_so_mau',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('products', 'tem_co_can_mang',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('products', 'tem_co_khuon_be',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('products', 'tem_co_uv',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('products', 'tem_co_suppo',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('products', 'tem_co_luoi',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('products', 'tem_hai_manh',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('products', 'tem_khac_thiet_ke',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.add_column('sales_orders', sa.Column('nv_theo_doi_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sales_orders', 'users', ['nv_theo_doi_id'], ['id'])
    op.drop_index('ix_tai_san_in_sp_san_pham_id', table_name='tai_san_in_san_pham')
    op.drop_index('ix_tai_san_in_sp_tai_san_id', table_name='tai_san_in_san_pham')
    op.create_index(op.f('ix_tai_san_in_san_pham_san_pham_id'), 'tai_san_in_san_pham', ['san_pham_id'], unique=False)
    op.create_index(op.f('ix_tai_san_in_san_pham_tai_san_id'), 'tai_san_in_san_pham', ['tai_san_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tai_san_in_san_pham_tai_san_id'), table_name='tai_san_in_san_pham')
    op.drop_index(op.f('ix_tai_san_in_san_pham_san_pham_id'), table_name='tai_san_in_san_pham')
    op.create_index('ix_tai_san_in_sp_tai_san_id', 'tai_san_in_san_pham', ['tai_san_id'], unique=False)
    op.create_index('ix_tai_san_in_sp_san_pham_id', 'tai_san_in_san_pham', ['san_pham_id'], unique=False)
    op.drop_constraint(None, 'sales_orders', type_='foreignkey')
    op.drop_column('sales_orders', 'nv_theo_doi_id')
    op.alter_column('products', 'tem_khac_thiet_ke',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('products', 'tem_hai_manh',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('products', 'tem_co_luoi',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('products', 'tem_co_suppo',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('products', 'tem_co_uv',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('products', 'tem_co_khuon_be',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('products', 'tem_co_can_mang',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('products', 'tem_so_mau',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('products', 'tem_waste_to',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('products', 'tem_sp_per_to',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('products', 'co_tem_offset',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('products', 'do_phu',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('products', 'do_kho',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('products', 'be_lo',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('products', 'co_be',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('products', 'be_hai_manh',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###
