"""add_in_2_lan_to_production_orders

Revision ID: 7cdcd6800431
Revises: 8bd5097644f7
Create Date: 2026-06-28 16:18:50.343200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cdcd6800431'
down_revision: Union[str, None] = '8bd5097644f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('production_orders', sa.Column('in_2_lan', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('production_orders', 'in_2_lan')
    # ### end Alembic commands ###
