"""add replacement_do_id to sales_returns

Revision ID: 7e47cb333037
Revises: 84898a9bb8c2
Create Date: 2026-06-26 20:54:47.410655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7e47cb333037'
down_revision: Union[str, None] = '84898a9bb8c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_mi_production_session', 'material_issues', type_='foreignkey')
    op.create_foreign_key(None, 'material_issues', 'production_sessions', ['production_session_id'], ['id'])
    op.alter_column('production_khau_costs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_index('ix_production_khau_costs_poi', table_name='production_khau_costs')
    op.create_index(op.f('ix_production_khau_costs_production_order_item_id'), 'production_khau_costs', ['production_order_item_id'], unique=False)
    op.drop_index('ix_production_outputs_session', table_name='production_outputs')
    op.create_index(op.f('ix_production_outputs_production_session_id'), 'production_outputs', ['production_session_id'], unique=False)
    op.drop_index('ix_production_session_overheads_session', table_name='production_session_overheads')
    op.create_index(op.f('ix_production_session_overheads_session_id'), 'production_session_overheads', ['session_id'], unique=False)
    op.add_column('sales_returns', sa.Column('replacement_do_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sales_returns', 'delivery_orders', ['replacement_do_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sales_returns', type_='foreignkey')
    op.drop_column('sales_returns', 'replacement_do_id')
    op.drop_index(op.f('ix_production_session_overheads_session_id'), table_name='production_session_overheads')
    op.create_index('ix_production_session_overheads_session', 'production_session_overheads', ['session_id'], unique=False)
    op.drop_index(op.f('ix_production_outputs_production_session_id'), table_name='production_outputs')
    op.create_index('ix_production_outputs_session', 'production_outputs', ['production_session_id'], unique=False)
    op.drop_index(op.f('ix_production_khau_costs_production_order_item_id'), table_name='production_khau_costs')
    op.create_index('ix_production_khau_costs_poi', 'production_khau_costs', ['production_order_item_id'], unique=False)
    op.alter_column('production_khau_costs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_constraint(None, 'material_issues', type_='foreignkey')
    op.create_foreign_key('fk_mi_production_session', 'material_issues', 'production_sessions', ['production_session_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
