"""add_phan_xuong_id_to_sales_orders

Revision ID: 8b5a8d8f675a
Revises: d3e4f5a6b7c8
Create Date: 2026-05-02 19:19:28.950401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b5a8d8f675a'
down_revision: Union[str, None] = 'd3e4f5a6b7c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'delivery_order_items', 'production_orders', ['production_order_id'], ['id'])
    op.create_foreign_key(None, 'delivery_orders', 'tai_xe', ['tai_xe_id'], ['id'])
    op.create_foreign_key(None, 'delivery_orders', 'xe', ['xe_id'], ['id'])
    op.create_foreign_key(None, 'delivery_orders', 'don_gia_van_chuyen', ['don_gia_vc_id'], ['id'])
    op.create_foreign_key(None, 'delivery_orders', 'yeu_cau_giao_hang', ['yeu_cau_id'], ['id'])
    op.create_foreign_key(None, 'phieu_nhap_phoi_song', 'warehouses', ['warehouse_id'], ['id'])
    op.create_foreign_key(None, 'sales_orders', 'phan_xuong', ['phan_xuong_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sales_orders', type_='foreignkey')
    op.drop_column('sales_orders', 'phan_xuong_id')
    op.drop_constraint(None, 'phieu_nhap_phoi_song', type_='foreignkey')
    op.drop_constraint(None, 'delivery_orders', type_='foreignkey')
    op.drop_constraint(None, 'delivery_orders', type_='foreignkey')
    op.drop_constraint(None, 'delivery_orders', type_='foreignkey')
    op.drop_constraint(None, 'delivery_orders', type_='foreignkey')
    op.drop_constraint(None, 'delivery_order_items', type_='foreignkey')
    # ### end Alembic commands ###
