"""add_order_cost_vat_fields

Revision ID: a18622fac251
Revises: 72a4eb5c34cf
Create Date: 2026-06-30 21:30:50.329180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a18622fac251'
down_revision: Union[str, None] = '72a4eb5c34cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales_orders', sa.Column('chi_phi_bang_in', sa.Numeric(precision=18, scale=2), nullable=False, server_default='0'))
    op.add_column('sales_orders', sa.Column('chi_phi_khuon', sa.Numeric(precision=18, scale=2), nullable=False, server_default='0'))
    op.add_column('sales_orders', sa.Column('chi_phi_van_chuyen', sa.Numeric(precision=18, scale=2), nullable=False, server_default='0'))
    op.add_column('sales_orders', sa.Column('ty_le_vat', sa.Numeric(precision=5, scale=2), nullable=False, server_default='8'))
    op.add_column('sales_orders', sa.Column('tien_vat', sa.Numeric(precision=18, scale=2), nullable=False, server_default='0'))
    op.add_column('sales_orders', sa.Column('dieu_khoan', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales_orders', 'dieu_khoan')
    op.drop_column('sales_orders', 'tien_vat')
    op.drop_column('sales_orders', 'ty_le_vat')
    op.drop_column('sales_orders', 'chi_phi_van_chuyen')
    op.drop_column('sales_orders', 'chi_phi_khuon')
    op.drop_column('sales_orders', 'chi_phi_bang_in')
    # ### end Alembic commands ###
