"""add_phieu_in_id_to_production_outputs

Revision ID: cd3b9064650c
Revises: da1f6657a415
Create Date: 2026-06-28 11:43:09.626925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd3b9064650c'
down_revision: Union[str, None] = 'da1f6657a415'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_defect_records_phan_xuong_id', table_name='defect_records')
    op.drop_index('ix_defect_records_phap_nhan_id', table_name='defect_records')
    op.add_column('production_outputs', sa.Column('phieu_in_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_production_outputs_phieu_in_id'), 'production_outputs', ['phieu_in_id'], unique=False)
    op.create_foreign_key(None, 'production_outputs', 'phieu_in', ['phieu_in_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'production_outputs', type_='foreignkey')
    op.drop_index(op.f('ix_production_outputs_phieu_in_id'), table_name='production_outputs')
    op.drop_column('production_outputs', 'phieu_in_id')
    op.create_index('ix_defect_records_phap_nhan_id', 'defect_records', ['phap_nhan_id'], unique=False)
    op.create_index('ix_defect_records_phan_xuong_id', 'defect_records', ['phan_xuong_id'], unique=False)
    # ### end Alembic commands ###
