"""add may_sau_in_id to printer_user

Revision ID: e966463514b4
Revises: pu001_printer_user_fk_to_may_in
Create Date: 2026-05-18 23:07:10.523232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e966463514b4'
down_revision: Union[str, None] = 'pu001_printer_user_fk_to_may_in'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agent_sessions', 'session_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('audit_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_index('user_id', table_name='audit_logs')
    op.create_foreign_key(None, 'audit_logs', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'cash_payments', 'phap_nhan', ['phap_nhan_id'], ['id'])
    op.create_foreign_key(None, 'cash_receipts', 'phap_nhan', ['phap_nhan_id'], ['id'])
    op.alter_column('cau_truc_thong_dung', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('cau_truc_thong_dung', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('customers', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('customers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_index('idx_customers_trang_thai', table_name='customers')
    op.drop_index('nv_phu_trach_id', table_name='customers')
    op.create_foreign_key(None, 'customers', 'users', ['nv_phu_trach_id'], ['id'])
    op.alter_column('don_gia_van_chuyen', 'don_gia_m2',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('don_gia_van_chuyen', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('don_vi_tinh', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_index('idx_gr_items_po_item', table_name='goods_receipt_items')
    op.drop_index('idx_gr_items_receipt', table_name='goods_receipt_items')
    op.drop_index('idx_gr_po', table_name='goods_receipts')
    op.drop_index('idx_gr_trang_thai', table_name='goods_receipts')
    op.create_foreign_key(None, 'goods_receipts', 'phap_nhan', ['phap_nhan_id'], ['id'])
    op.drop_index('idx_att_emp_ngay', table_name='hr_attendance_logs')
    op.alter_column('hr_contracts', 'phu_cap_chuyen_can',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('hr_contracts', 'phu_cap_trach_nhiem',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('hr_contracts', 'phu_cap_nha_o_com',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('hr_contracts', 'phu_cap_dien_thoai',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('hr_contracts', 'phu_cap_khac',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('hr_employees', 'he_so_ca_nhan',
               existing_type=sa.NUMERIC(precision=4, scale=2),
               nullable=False,
               existing_server_default=sa.text('1.5'))
    op.alter_column('hr_employees', 'is_tai_xe',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index('idx_hr_emp_bo_phan', table_name='hr_employees')
    op.drop_index('idx_hr_emp_trang_thai', table_name='hr_employees')
    op.alter_column('hr_payroll_configs', 'ma_cau_hinh',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('hr_payroll_configs', 'ten_cau_hinh',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.alter_column('hr_payroll_configs', 'gia_tri',
               existing_type=sa.NUMERIC(precision=14, scale=4),
               nullable=True)
    op.drop_constraint('hr_payroll_configs_ma_cau_hinh_key', 'hr_payroll_configs', type_='unique')
    op.create_unique_constraint(None, 'hr_payroll_configs', ['ma_hang'])
    op.alter_column('hr_payroll_holidays', 'trang_thai',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('hr_payroll_holidays', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('hr_payroll_runs', 'luong_co_ban_phu_cap',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('hr_payroll_runs', 'ngay_cong_nguyen_luong',
               existing_type=sa.NUMERIC(precision=8, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('hr_payroll_runs', 'gio_cong_thuc_te',
               existing_type=sa.NUMERIC(precision=8, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('hr_payroll_runs', 'luong_theo_ngay_cong',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('hr_payroll_runs', 'ot_gio_ngay_thuong',
               existing_type=sa.NUMERIC(precision=8, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('hr_payroll_runs', 'ot_gio_chu_nhat',
               existing_type=sa.NUMERIC(precision=8, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('hr_payroll_runs', 'ot_gio_chu_nhat_tang_ca',
               existing_type=sa.NUMERIC(precision=8, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('hr_payroll_runs', 'ot_gio_ngay_le',
               existing_type=sa.NUMERIC(precision=8, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('hr_payroll_runs', 'ot_tien_ngay_thuong',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('hr_payroll_runs', 'ot_tien_chu_nhat',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('hr_payroll_runs', 'ot_tien_chu_nhat_tang_ca',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('hr_payroll_runs', 'ot_tien_ngay_le',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('hr_payroll_runs', 'phu_cap_chuyen_can',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('hr_payroll_runs', 'phu_cap_trach_nhiem',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('hr_payroll_runs', 'phu_cap_nha_o_com',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('hr_payroll_runs', 'phu_cap_dien_thoai',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('hr_payroll_runs', 'phu_cap_khac',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('hr_payroll_runs', 'tien_chuyen_hqcv_thanh_tich',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('hr_payroll_runs', 'tong_thu_nhap',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_index('idx_payroll_emp', table_name='hr_payroll_runs')
    op.drop_index('idx_payroll_thang', table_name='hr_payroll_runs')
    op.alter_column('inventory_balances', 'cap_nhat_luc',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_index('idx_inv_bal_wh_paper', table_name='inventory_balances')
    op.drop_index('idx_inv_bal_wh_prod', table_name='inventory_balances')
    op.drop_index('other_material_id', table_name='inventory_balances')
    op.drop_index('paper_material_id', table_name='inventory_balances')
    op.drop_index('product_id', table_name='inventory_balances')
    op.drop_index('warehouse_id', table_name='inventory_balances')
    op.create_foreign_key(None, 'inventory_balances', 'warehouses', ['warehouse_id'], ['id'])
    op.create_foreign_key(None, 'inventory_balances', 'products', ['product_id'], ['id'])
    op.create_foreign_key(None, 'inventory_balances', 'paper_materials', ['paper_material_id'], ['id'])
    op.create_foreign_key(None, 'inventory_balances', 'other_materials', ['other_material_id'], ['id'])
    op.alter_column('inventory_transactions', 'ngay_giao_dich',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('inventory_transactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_index('created_by', table_name='inventory_transactions')
    op.drop_index('idx_inv_trans_wh_date', table_name='inventory_transactions')
    op.drop_index('paper_roll_id', table_name='inventory_transactions')
    op.create_foreign_key(None, 'inventory_transactions', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'inventory_transactions', 'paper_rolls', ['paper_roll_id'], ['id'])
    op.create_foreign_key(None, 'inventory_transactions', 'other_materials', ['other_material_id'], ['id'])
    op.create_foreign_key(None, 'inventory_transactions', 'paper_materials', ['paper_material_id'], ['id'])
    op.create_foreign_key(None, 'inventory_transactions', 'warehouses', ['warehouse_id'], ['id'])
    op.create_foreign_key(None, 'inventory_transactions', 'products', ['product_id'], ['id'])
    op.create_foreign_key(None, 'journal_entries', 'phap_nhan', ['phap_nhan_id'], ['id'])
    op.create_foreign_key(None, 'journal_entries', 'phan_xuong', ['phan_xuong_id'], ['id'])
    op.alter_column('lo_xe', 'he_so_chuyen',
               existing_type=sa.NUMERIC(precision=8, scale=4),
               nullable=False,
               existing_server_default=sa.text('0.3'))
    op.alter_column('lo_xe', 'trang_thai',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('lo_xe', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('machines', 'loai_may',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'khac'::character varying"))
    op.alter_column('machines', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('machines', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('machines', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('material_groups', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('may_dung_log', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_may_dung_log_ngay', table_name='may_dung_log')
    op.drop_index('ix_may_dung_log_production_order_id', table_name='may_dung_log')
    op.alter_column('other_materials', 'ma_amis',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=50),
               existing_nullable=True,
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('other_materials', 'ten',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('other_materials', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('other_materials', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_index('ma_ncc_id', table_name='other_materials')
    op.create_foreign_key(None, 'other_materials', 'suppliers', ['ma_ncc_id'], ['id'])
    op.create_foreign_key(None, 'other_materials', 'material_groups', ['ma_nhom_id'], ['id'])
    op.alter_column('paper_materials', 'ten',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('paper_materials', 'ten_viet_tat',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=100),
               existing_nullable=True,
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('paper_materials', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('paper_materials', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_index('ma_nhom_id', table_name='paper_materials')
    op.drop_index('ma_nsx_id', table_name='paper_materials')
    op.create_foreign_key(None, 'paper_materials', 'suppliers', ['ma_nsx_id'], ['id'])
    op.create_foreign_key(None, 'paper_materials', 'material_groups', ['ma_nhom_id'], ['id'])
    op.alter_column('paper_rolls', 'ngay_nhap',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('paper_rolls', 'ngay_xuat_gan_nhat',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('paper_rolls', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('paper_rolls', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.create_foreign_key(None, 'paper_rolls', 'paper_materials', ['paper_material_id'], ['id'])
    op.create_foreign_key(None, 'paper_rolls', 'warehouses', ['warehouse_id'], ['id'])
    op.drop_index('idx_permissions_ma_quyen', table_name='permissions')
    op.drop_index('idx_permissions_nhom', table_name='permissions')
    op.create_foreign_key(None, 'phan_xuong', 'phap_nhan', ['phap_nhan_id'], ['id'])
    op.drop_index('ix_phieu_in_state_log_changed_at', table_name='phieu_in_state_log')
    op.drop_index('ix_phieu_in_state_log_phieu_in_id', table_name='phieu_in_state_log')
    op.drop_index('tinh_id', table_name='phuong_xa')
    op.create_foreign_key(None, 'phuong_xa', 'tinh_thanh', ['tinh_id'], ['id'])
    op.drop_index('uq_print_templates_default', table_name='print_templates', postgresql_where='(phap_nhan_id IS NULL)')
    op.drop_index('uq_print_templates_per_pn', table_name='print_templates', postgresql_where='(phap_nhan_id IS NOT NULL)')
    op.add_column('printer_user', sa.Column('may_sau_in_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'printer_user', 'may_sau_in', ['may_sau_in_id'], ['id'])
    op.drop_index('bom_id', table_name='production_bom_items')
    op.create_foreign_key(None, 'production_bom_items', 'paper_materials', ['paper_material_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'production_bom_items', 'production_boms', ['bom_id'], ['id'], ondelete='CASCADE')
    op.alter_column('production_boms', 'dan',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('production_boms', 'ghim',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('production_boms', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('production_boms', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.create_foreign_key(None, 'production_boms', 'production_order_items', ['production_order_item_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'production_boms', 'users', ['created_by'], ['id'])
    op.alter_column('production_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_prod_logs_machine_date', table_name='production_logs')
    op.drop_index('idx_prod_logs_order', table_name='production_logs')
    op.drop_index('idx_po_items_order', table_name='production_order_items')
    op.drop_index('production_order_id', table_name='production_order_items')
    op.drop_index('sales_order_item_id', table_name='production_order_items')
    op.create_foreign_key(None, 'production_order_items', 'production_orders', ['production_order_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'production_order_items', 'products', ['product_id'], ['id'])
    op.create_foreign_key(None, 'production_order_items', 'sales_order_items', ['sales_order_item_id'], ['id'])
    op.alter_column('production_orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('production_orders', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_index('idx_prod_phan_xuong', table_name='production_orders')
    op.drop_index('idx_prod_trang_thai', table_name='production_orders')
    op.drop_index('sales_order_id', table_name='production_orders')
    op.create_foreign_key(None, 'production_orders', 'warehouses', ['kho_sx_id'], ['id'])
    op.create_foreign_key(None, 'production_orders', 'phap_nhan', ['phap_nhan_id'], ['id'])
    op.create_foreign_key(None, 'production_orders', 'users', ['nv_theo_doi_id'], ['id'])
    op.create_foreign_key(None, 'production_orders', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'production_orders', 'sales_orders', ['sales_order_id'], ['id'])
    op.create_foreign_key(None, 'production_orders', 'phan_xuong', ['phan_xuong_id'], ['id'])
    op.drop_index('idx_prod_plan_trang_thai', table_name='production_plans')
    op.alter_column('products', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('products', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_index('ma_kh_id', table_name='products')
    op.create_foreign_key(None, 'products', 'customers', ['ma_kh_id'], ['id'])
    op.drop_index('idx_purchase_inv_trang_thai', table_name='purchase_invoices')
    op.create_foreign_key(None, 'purchase_invoices', 'phap_nhan', ['phap_nhan_id'], ['id'])
    op.alter_column('purchase_orders', 'loai_po',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'chung'::character varying"))
    op.drop_index('idx_po_ngay', table_name='purchase_orders')
    op.drop_index('idx_po_supplier', table_name='purchase_orders')
    op.drop_index('idx_po_trang_thai', table_name='purchase_orders')
    op.drop_constraint('purchase_requisition_items_ymh_id_fkey', 'purchase_requisition_items', type_='foreignkey')
    op.create_foreign_key(None, 'purchase_requisition_items', 'purchase_requisitions', ['ymh_id'], ['id'])
    op.alter_column('purchase_requisitions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('purchase_requisitions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('quote_id', table_name='quote_items')
    op.create_foreign_key(None, 'quote_items', 'quotes', ['quote_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'quote_items', 'products', ['product_id'], ['id'])
    op.alter_column('quotes', 'approved_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('quotes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('quotes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_index('approved_by', table_name='quotes')
    op.drop_index('customer_id', table_name='quotes')
    op.drop_index('nguoi_duyet_id', table_name='quotes')
    op.create_foreign_key(None, 'quotes', 'users', ['nv_theo_doi_id'], ['id'])
    op.create_foreign_key(None, 'quotes', 'phan_xuong', ['phan_xuong_id'], ['id'])
    op.create_foreign_key(None, 'quotes', 'customers', ['customer_id'], ['id'])
    op.create_foreign_key(None, 'quotes', 'users', ['nv_phu_trach_id'], ['id'])
    op.create_foreign_key(None, 'quotes', 'users', ['approved_by'], ['id'])
    op.create_foreign_key(None, 'quotes', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'quotes', 'users', ['nguoi_duyet_id'], ['id'])
    op.create_foreign_key(None, 'quotes', 'phap_nhan', ['phap_nhan_id'], ['id'])
    op.drop_index('idx_role_permissions_permission_id', table_name='role_permissions')
    op.drop_index('idx_role_permissions_role_id', table_name='role_permissions')
    op.drop_constraint('role_permissions_role_id_permission_id_key', 'role_permissions', type_='unique')
    op.drop_constraint('role_permissions_permission_id_fkey', 'role_permissions', type_='foreignkey')
    op.drop_constraint('role_permissions_role_id_fkey', 'role_permissions', type_='foreignkey')
    op.create_foreign_key(None, 'role_permissions', 'roles', ['role_id'], ['id'])
    op.create_foreign_key(None, 'role_permissions', 'permissions', ['permission_id'], ['id'])
    op.alter_column('roles', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_index('idx_sales_inv_trang_thai', table_name='sales_invoices')
    op.create_foreign_key(None, 'sales_invoices', 'phap_nhan', ['phap_nhan_id'], ['id'])
    op.alter_column('sales_order_items', 'ty_le_giam_gia',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False)
    op.alter_column('sales_order_items', 'so_tien_giam_gia',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=False)
    op.drop_index('idx_so_items_order', table_name='sales_order_items')
    op.drop_index('order_id', table_name='sales_order_items')
    op.create_foreign_key(None, 'sales_order_items', 'sales_orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'sales_order_items', 'products', ['product_id'], ['id'])
    op.create_foreign_key(None, 'sales_order_items', 'quote_items', ['quote_item_id'], ['id'], ondelete='SET NULL')
    op.alter_column('sales_orders', 'ty_le_giam_gia',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False)
    op.alter_column('sales_orders', 'so_tien_giam_gia',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=False)
    op.alter_column('sales_orders', 'tong_tien_sau_giam',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=False)
    op.alter_column('sales_orders', 'approved_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('sales_orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('sales_orders', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_index('idx_so_customer', table_name='sales_orders')
    op.drop_index('idx_so_trang_thai', table_name='sales_orders')
    op.drop_index('nv_kinh_doanh_id', table_name='sales_orders')
    op.create_foreign_key(None, 'sales_orders', 'phan_xuong', ['phan_xuong_id'], ['id'])
    op.create_foreign_key(None, 'sales_orders', 'phap_nhan', ['phap_nhan_id'], ['id'])
    op.create_foreign_key(None, 'sales_orders', 'customers', ['customer_id'], ['id'])
    op.create_foreign_key(None, 'sales_orders', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'sales_orders', 'phap_nhan', ['phap_nhan_sx_id'], ['id'])
    op.create_foreign_key(None, 'sales_orders', 'users', ['approved_by'], ['id'])
    op.create_foreign_key(None, 'sales_orders', 'users', ['nv_kinh_doanh_id'], ['id'])
    op.drop_index('ix_sales_return_items_delivery_order_item_id', table_name='sales_return_items')
    op.drop_constraint('fk_sales_return_items_delivery_order_item_id', 'sales_return_items', type_='foreignkey')
    op.create_foreign_key(None, 'sales_return_items', 'delivery_order_items', ['delivery_order_item_id'], ['id'])
    op.drop_index('idx_scan_log_machine_date', table_name='scan_log')
    op.alter_column('suppliers', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('suppliers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_index('idx_suppliers_trang_thai', table_name='suppliers')
    op.alter_column('tai_xe', 'he_so_chuyen',
               existing_type=sa.NUMERIC(precision=8, scale=4),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('tai_xe', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('users', 'lan_dang_nhap_cuoi',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_index('role_id', table_name='users')
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    op.alter_column('vi_tri', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('warehouses', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.create_foreign_key(None, 'warehouses', 'phan_xuong', ['phan_xuong_id'], ['id'])
    op.alter_column('xe', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('xe', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_constraint(None, 'warehouses', type_='foreignkey')
    op.alter_column('warehouses', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('vi_tri', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_index('role_id', 'users', ['role_id'], unique=False)
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('users', 'lan_dang_nhap_cuoi',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('tai_xe', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('tai_xe', 'he_so_chuyen',
               existing_type=sa.NUMERIC(precision=8, scale=4),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.create_index('idx_suppliers_trang_thai', 'suppliers', ['trang_thai'], unique=False)
    op.alter_column('suppliers', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('suppliers', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.create_index('idx_scan_log_machine_date', 'scan_log', ['may_scan_id', sa.text('created_at DESC')], unique=False)
    op.drop_constraint(None, 'sales_return_items', type_='foreignkey')
    op.create_foreign_key('fk_sales_return_items_delivery_order_item_id', 'sales_return_items', 'delivery_order_items', ['delivery_order_item_id'], ['id'], ondelete='SET NULL')
    op.create_index('ix_sales_return_items_delivery_order_item_id', 'sales_return_items', ['delivery_order_item_id'], unique=False)
    op.drop_constraint(None, 'sales_orders', type_='foreignkey')
    op.drop_constraint(None, 'sales_orders', type_='foreignkey')
    op.drop_constraint(None, 'sales_orders', type_='foreignkey')
    op.drop_constraint(None, 'sales_orders', type_='foreignkey')
    op.drop_constraint(None, 'sales_orders', type_='foreignkey')
    op.drop_constraint(None, 'sales_orders', type_='foreignkey')
    op.drop_constraint(None, 'sales_orders', type_='foreignkey')
    op.create_index('nv_kinh_doanh_id', 'sales_orders', ['nv_kinh_doanh_id'], unique=False)
    op.create_index('idx_so_trang_thai', 'sales_orders', ['trang_thai'], unique=False)
    op.create_index('idx_so_customer', 'sales_orders', ['customer_id'], unique=False)
    op.alter_column('sales_orders', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('sales_orders', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('sales_orders', 'approved_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('sales_orders', 'tong_tien_sau_giam',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=True)
    op.alter_column('sales_orders', 'so_tien_giam_gia',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=True)
    op.alter_column('sales_orders', 'ty_le_giam_gia',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True)
    op.drop_constraint(None, 'sales_order_items', type_='foreignkey')
    op.drop_constraint(None, 'sales_order_items', type_='foreignkey')
    op.drop_constraint(None, 'sales_order_items', type_='foreignkey')
    op.create_index('order_id', 'sales_order_items', ['order_id'], unique=False)
    op.create_index('idx_so_items_order', 'sales_order_items', ['order_id'], unique=False)
    op.alter_column('sales_order_items', 'so_tien_giam_gia',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=True)
    op.alter_column('sales_order_items', 'ty_le_giam_gia',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True)
    op.drop_constraint(None, 'sales_invoices', type_='foreignkey')
    op.create_index('idx_sales_inv_trang_thai', 'sales_invoices', ['trang_thai'], unique=False)
    op.alter_column('roles', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_constraint(None, 'role_permissions', type_='foreignkey')
    op.drop_constraint(None, 'role_permissions', type_='foreignkey')
    op.create_foreign_key('role_permissions_role_id_fkey', 'role_permissions', 'roles', ['role_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('role_permissions_permission_id_fkey', 'role_permissions', 'permissions', ['permission_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint('role_permissions_role_id_permission_id_key', 'role_permissions', ['role_id', 'permission_id'])
    op.create_index('idx_role_permissions_role_id', 'role_permissions', ['role_id'], unique=False)
    op.create_index('idx_role_permissions_permission_id', 'role_permissions', ['permission_id'], unique=False)
    op.drop_constraint(None, 'quotes', type_='foreignkey')
    op.drop_constraint(None, 'quotes', type_='foreignkey')
    op.drop_constraint(None, 'quotes', type_='foreignkey')
    op.drop_constraint(None, 'quotes', type_='foreignkey')
    op.drop_constraint(None, 'quotes', type_='foreignkey')
    op.drop_constraint(None, 'quotes', type_='foreignkey')
    op.drop_constraint(None, 'quotes', type_='foreignkey')
    op.drop_constraint(None, 'quotes', type_='foreignkey')
    op.create_index('nguoi_duyet_id', 'quotes', ['nguoi_duyet_id'], unique=False)
    op.create_index('customer_id', 'quotes', ['customer_id'], unique=False)
    op.create_index('approved_by', 'quotes', ['approved_by'], unique=False)
    op.alter_column('quotes', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('quotes', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('quotes', 'approved_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_constraint(None, 'quote_items', type_='foreignkey')
    op.drop_constraint(None, 'quote_items', type_='foreignkey')
    op.create_index('quote_id', 'quote_items', ['quote_id'], unique=False)
    op.alter_column('purchase_requisitions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('purchase_requisitions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'purchase_requisition_items', type_='foreignkey')
    op.create_foreign_key('purchase_requisition_items_ymh_id_fkey', 'purchase_requisition_items', 'purchase_requisitions', ['ymh_id'], ['id'], ondelete='CASCADE')
    op.create_index('idx_po_trang_thai', 'purchase_orders', ['trang_thai'], unique=False)
    op.create_index('idx_po_supplier', 'purchase_orders', ['supplier_id'], unique=False)
    op.create_index('idx_po_ngay', 'purchase_orders', ['ngay_po'], unique=False)
    op.alter_column('purchase_orders', 'loai_po',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'chung'::character varying"))
    op.drop_constraint(None, 'purchase_invoices', type_='foreignkey')
    op.create_index('idx_purchase_inv_trang_thai', 'purchase_invoices', ['trang_thai'], unique=False)
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_index('ma_kh_id', 'products', ['ma_kh_id'], unique=False)
    op.alter_column('products', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('products', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.create_index('idx_prod_plan_trang_thai', 'production_plans', ['trang_thai'], unique=False)
    op.drop_constraint(None, 'production_orders', type_='foreignkey')
    op.drop_constraint(None, 'production_orders', type_='foreignkey')
    op.drop_constraint(None, 'production_orders', type_='foreignkey')
    op.drop_constraint(None, 'production_orders', type_='foreignkey')
    op.drop_constraint(None, 'production_orders', type_='foreignkey')
    op.drop_constraint(None, 'production_orders', type_='foreignkey')
    op.create_index('sales_order_id', 'production_orders', ['sales_order_id'], unique=False)
    op.create_index('idx_prod_trang_thai', 'production_orders', ['trang_thai'], unique=False)
    op.create_index('idx_prod_phan_xuong', 'production_orders', ['phan_xuong_id'], unique=False)
    op.alter_column('production_orders', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('production_orders', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_constraint(None, 'production_order_items', type_='foreignkey')
    op.drop_constraint(None, 'production_order_items', type_='foreignkey')
    op.drop_constraint(None, 'production_order_items', type_='foreignkey')
    op.create_index('sales_order_item_id', 'production_order_items', ['sales_order_item_id'], unique=False)
    op.create_index('production_order_id', 'production_order_items', ['production_order_id'], unique=False)
    op.create_index('idx_po_items_order', 'production_order_items', ['production_order_id'], unique=False)
    op.create_index('idx_prod_logs_order', 'production_logs', ['production_order_id'], unique=False)
    op.create_index('idx_prod_logs_machine_date', 'production_logs', ['machine_id', sa.text('created_at DESC')], unique=False)
    op.alter_column('production_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'production_boms', type_='foreignkey')
    op.drop_constraint(None, 'production_boms', type_='foreignkey')
    op.alter_column('production_boms', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('production_boms', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('production_boms', 'ghim',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('production_boms', 'dan',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_constraint(None, 'production_bom_items', type_='foreignkey')
    op.drop_constraint(None, 'production_bom_items', type_='foreignkey')
    op.create_index('bom_id', 'production_bom_items', ['bom_id'], unique=False)
    op.drop_constraint(None, 'printer_user', type_='foreignkey')
    op.drop_column('printer_user', 'may_sau_in_id')
    op.create_index('uq_print_templates_per_pn', 'print_templates', ['ma_mau', 'phap_nhan_id'], unique=True, postgresql_where='(phap_nhan_id IS NOT NULL)')
    op.create_index('uq_print_templates_default', 'print_templates', ['ma_mau'], unique=True, postgresql_where='(phap_nhan_id IS NULL)')
    op.drop_constraint(None, 'phuong_xa', type_='foreignkey')
    op.create_index('tinh_id', 'phuong_xa', ['tinh_id'], unique=False)
    op.create_index('ix_phieu_in_state_log_phieu_in_id', 'phieu_in_state_log', ['phieu_in_id'], unique=False)
    op.create_index('ix_phieu_in_state_log_changed_at', 'phieu_in_state_log', ['changed_at'], unique=False)
    op.drop_constraint(None, 'phan_xuong', type_='foreignkey')
    op.create_index('idx_permissions_nhom', 'permissions', ['nhom'], unique=False)
    op.create_index('idx_permissions_ma_quyen', 'permissions', ['ma_quyen'], unique=False)
    op.drop_constraint(None, 'paper_rolls', type_='foreignkey')
    op.drop_constraint(None, 'paper_rolls', type_='foreignkey')
    op.alter_column('paper_rolls', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('paper_rolls', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('paper_rolls', 'ngay_xuat_gan_nhat',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('paper_rolls', 'ngay_nhap',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_constraint(None, 'paper_materials', type_='foreignkey')
    op.drop_constraint(None, 'paper_materials', type_='foreignkey')
    op.create_index('ma_nsx_id', 'paper_materials', ['ma_nsx_id'], unique=False)
    op.create_index('ma_nhom_id', 'paper_materials', ['ma_nhom_id'], unique=False)
    op.alter_column('paper_materials', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('paper_materials', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('paper_materials', 'ten_viet_tat',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True,
               existing_server_default=sa.text('NULL::character varying'))
    op.alter_column('paper_materials', 'ten',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
    op.drop_constraint(None, 'other_materials', type_='foreignkey')
    op.drop_constraint(None, 'other_materials', type_='foreignkey')
    op.create_index('ma_ncc_id', 'other_materials', ['ma_ncc_id'], unique=False)
    op.alter_column('other_materials', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('other_materials', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('other_materials', 'ten',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
    op.alter_column('other_materials', 'ma_amis',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True,
               existing_server_default=sa.text('NULL::character varying'))
    op.create_index('ix_may_dung_log_production_order_id', 'may_dung_log', ['production_order_id'], unique=False)
    op.create_index('ix_may_dung_log_ngay', 'may_dung_log', ['ngay'], unique=False)
    op.alter_column('may_dung_log', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('material_groups', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('machines', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('machines', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('machines', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('machines', 'loai_may',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'khac'::character varying"))
    op.alter_column('lo_xe', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('lo_xe', 'trang_thai',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('lo_xe', 'he_so_chuyen',
               existing_type=sa.NUMERIC(precision=8, scale=4),
               nullable=True,
               existing_server_default=sa.text('0.3'))
    op.drop_constraint(None, 'journal_entries', type_='foreignkey')
    op.drop_constraint(None, 'journal_entries', type_='foreignkey')
    op.drop_constraint(None, 'inventory_transactions', type_='foreignkey')
    op.drop_constraint(None, 'inventory_transactions', type_='foreignkey')
    op.drop_constraint(None, 'inventory_transactions', type_='foreignkey')
    op.drop_constraint(None, 'inventory_transactions', type_='foreignkey')
    op.drop_constraint(None, 'inventory_transactions', type_='foreignkey')
    op.drop_constraint(None, 'inventory_transactions', type_='foreignkey')
    op.create_index('paper_roll_id', 'inventory_transactions', ['paper_roll_id'], unique=False)
    op.create_index('idx_inv_trans_wh_date', 'inventory_transactions', ['warehouse_id', sa.text('created_at DESC')], unique=False)
    op.create_index('created_by', 'inventory_transactions', ['created_by'], unique=False)
    op.alter_column('inventory_transactions', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('inventory_transactions', 'ngay_giao_dich',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_constraint(None, 'inventory_balances', type_='foreignkey')
    op.drop_constraint(None, 'inventory_balances', type_='foreignkey')
    op.drop_constraint(None, 'inventory_balances', type_='foreignkey')
    op.drop_constraint(None, 'inventory_balances', type_='foreignkey')
    op.create_index('warehouse_id', 'inventory_balances', ['warehouse_id'], unique=False)
    op.create_index('product_id', 'inventory_balances', ['product_id'], unique=False)
    op.create_index('paper_material_id', 'inventory_balances', ['paper_material_id'], unique=False)
    op.create_index('other_material_id', 'inventory_balances', ['other_material_id'], unique=False)
    op.create_index('idx_inv_bal_wh_prod', 'inventory_balances', ['warehouse_id', 'product_id'], unique=False)
    op.create_index('idx_inv_bal_wh_paper', 'inventory_balances', ['warehouse_id', 'paper_material_id'], unique=False)
    op.alter_column('inventory_balances', 'cap_nhat_luc',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.create_index('idx_payroll_thang', 'hr_payroll_runs', ['thang'], unique=False)
    op.create_index('idx_payroll_emp', 'hr_payroll_runs', ['employee_id'], unique=False)
    op.alter_column('hr_payroll_runs', 'tong_thu_nhap',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('hr_payroll_runs', 'tien_chuyen_hqcv_thanh_tich',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('hr_payroll_runs', 'phu_cap_khac',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('hr_payroll_runs', 'phu_cap_dien_thoai',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('hr_payroll_runs', 'phu_cap_nha_o_com',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('hr_payroll_runs', 'phu_cap_trach_nhiem',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('hr_payroll_runs', 'phu_cap_chuyen_can',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('hr_payroll_runs', 'ot_tien_ngay_le',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('hr_payroll_runs', 'ot_tien_chu_nhat_tang_ca',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('hr_payroll_runs', 'ot_tien_chu_nhat',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('hr_payroll_runs', 'ot_tien_ngay_thuong',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('hr_payroll_runs', 'ot_gio_ngay_le',
               existing_type=sa.NUMERIC(precision=8, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('hr_payroll_runs', 'ot_gio_chu_nhat_tang_ca',
               existing_type=sa.NUMERIC(precision=8, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('hr_payroll_runs', 'ot_gio_chu_nhat',
               existing_type=sa.NUMERIC(precision=8, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('hr_payroll_runs', 'ot_gio_ngay_thuong',
               existing_type=sa.NUMERIC(precision=8, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('hr_payroll_runs', 'luong_theo_ngay_cong',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('hr_payroll_runs', 'gio_cong_thuc_te',
               existing_type=sa.NUMERIC(precision=8, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('hr_payroll_runs', 'ngay_cong_nguyen_luong',
               existing_type=sa.NUMERIC(precision=8, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('hr_payroll_runs', 'luong_co_ban_phu_cap',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('hr_payroll_holidays', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('hr_payroll_holidays', 'trang_thai',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_constraint(None, 'hr_payroll_configs', type_='unique')
    op.create_unique_constraint('hr_payroll_configs_ma_cau_hinh_key', 'hr_payroll_configs', ['ma_cau_hinh'])
    op.alter_column('hr_payroll_configs', 'gia_tri',
               existing_type=sa.NUMERIC(precision=14, scale=4),
               nullable=False)
    op.alter_column('hr_payroll_configs', 'ten_cau_hinh',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.alter_column('hr_payroll_configs', 'ma_cau_hinh',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.create_index('idx_hr_emp_trang_thai', 'hr_employees', ['trang_thai'], unique=False)
    op.create_index('idx_hr_emp_bo_phan', 'hr_employees', ['bo_phan_id'], unique=False)
    op.alter_column('hr_employees', 'is_tai_xe',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('hr_employees', 'he_so_ca_nhan',
               existing_type=sa.NUMERIC(precision=4, scale=2),
               nullable=True,
               existing_server_default=sa.text('1.5'))
    op.alter_column('hr_contracts', 'phu_cap_khac',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('hr_contracts', 'phu_cap_dien_thoai',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('hr_contracts', 'phu_cap_nha_o_com',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('hr_contracts', 'phu_cap_trach_nhiem',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('hr_contracts', 'phu_cap_chuyen_can',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.create_index('idx_att_emp_ngay', 'hr_attendance_logs', ['employee_id', 'ngay'], unique=False)
    op.drop_constraint(None, 'goods_receipts', type_='foreignkey')
    op.create_index('idx_gr_trang_thai', 'goods_receipts', ['trang_thai'], unique=False)
    op.create_index('idx_gr_po', 'goods_receipts', ['po_id'], unique=False)
    op.create_index('idx_gr_items_receipt', 'goods_receipt_items', ['receipt_id'], unique=False)
    op.create_index('idx_gr_items_po_item', 'goods_receipt_items', ['po_item_id'], unique=False)
    op.alter_column('don_vi_tinh', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('don_gia_van_chuyen', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('don_gia_van_chuyen', 'don_gia_m2',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.create_index('nv_phu_trach_id', 'customers', ['nv_phu_trach_id'], unique=False)
    op.create_index('idx_customers_trang_thai', 'customers', ['trang_thai'], unique=False)
    op.alter_column('customers', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('customers', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('cau_truc_thong_dung', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('cau_truc_thong_dung', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_constraint(None, 'cash_receipts', type_='foreignkey')
    op.drop_constraint(None, 'cash_payments', type_='foreignkey')
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.create_index('user_id', 'audit_logs', ['user_id'], unique=False)
    op.alter_column('audit_logs', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('agent_sessions', 'session_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
